# Generated by Django 5.1 on 2024-09-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElixirModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('age', models.IntegerField(max_length=2)),
                ('salary', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
