# Generated by Django 5.1 on 2024-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_elixirmodel_delete_geeksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elixirmodel',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='elixirmodel',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
