# Generated by Django 5.1 on 2024-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_elixirmodel_age_alter_elixirmodel_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='elixirmodel',
            name='password',
            field=models.CharField(default='123456789', max_length=15),
        ),
    ]
