# Generated by Django 5.1 on 2024-09-27 06:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_elixirmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='elixirmodel',
            name='email',
            field=models.EmailField(blank=True, default='@elixir.com', max_length=254),
        ),
        migrations.AddField(
            model_name='elixirmodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='9876543210', max_length=128, region='IN'),
        ),
        migrations.AlterField(
            model_name='elixirmodel',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
