# Generated by Django 5.1 on 2024-10-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='elixirmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
