# Generated by Django 5.1 on 2024-10-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_elixirmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='elixirmodel',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
