# Generated by Django 5.1 on 2024-10-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_elixirmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elixirmodel',
            old_name='description',
            new_name='img_description',
        ),
    ]
