# Generated by Django 5.1 on 2024-10-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_maritalstatus_elixirmodel_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elixirmodel',
            name='img_description',
        ),
    ]
