# Generated by Django 5.1 on 2024-10-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_remove_elixirmodel_img_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfBirth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='elixirmodel',
            name='img_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='elixirmodel',
            name='date_of_birth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.dateofbirth'),
        ),
    ]
