# Generated by Django 5.1 on 2024-10-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_dateofbirth_elixirmodel_img_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elixirmodel',
            name='img_description',
        ),
    ]
