# Generated by Django 5.1 on 2024-10-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_remove_elixirmodel_img_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elixirmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
