# Generated by Django 5.1 on 2024-10-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_alter_elixirmodel_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elixirmodel',
            name='age',
        ),
        migrations.AlterField(
            model_name='elixirmodel',
            name='date_of_birth',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.dateofbirth'),
        ),
    ]
