# Generated by Django 5.1 on 2024-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_remove_elixirmodel_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elixirmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
