# Generated by Django 5.1 on 2024-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_alter_elixirmodel_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='elixirmodel',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
